import SwiftUI
import IdensicMobileSDK

/// A thin wrapper that presents Sumsub`s IdensicMobileSDK flow (document upload + liveness).
/// Pass a valid `accessToken` generated by your backend. The `onResult` callback delivers
/// the final approval flag (`true` = approved, `false` otherwise).
struct SumsubView: UIViewControllerRepresentable {
    let accessToken: String
    var onResult: ((Bool) -> Void)? = nil

    func makeUIViewController(context: Context) -> UIViewController {
        return SumsubHostController(accessToken: accessToken, onResult: onResult)
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
}

// MARK: - Internal host controller
private final class SumsubHostController: UIViewController {
    private let sdk: SNSMobileSDK
    private var onResult: ((Bool) -> Void)?
    private var hasPresented = false

    init(accessToken: String, onResult: ((Bool) -> Void)?) {
        self.sdk = SNSMobileSDK(accessToken: accessToken)
        self.onResult = onResult
        super.init(nibName: nil, bundle: nil)
        configureSDK()
    }

    @available(*, unavailable)
    required init?(coder: NSCoder) { fatalError("init(coder:) has not been implemented") }

    private func configureSDK() {
        guard sdk.isReady else {
            print("[Sumsub] SDK not ready: \(sdk.verboseStatus)")
            return
        }

        // Handle final decision
        sdk.verificationHandler { [weak self] approved in
            self?.onResult?(approved)
        }

        // Dismiss callback – treat as rejection if user quits early
        sdk.dismissHandler { [weak self] _, mainVC in
            mainVC.presentingViewController?.dismiss(animated: true, completion: nil)
            self?.onResult?(false)
        }

        // TODO: Provide real refresh token logic here
        sdk.tokenExpirationHandler { onComplete in
            // Fetch new token from backend then call onComplete(newToken)
            onComplete(nil)
        }
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        guard !hasPresented else { return }
        hasPresented = true
        present(sdk.mainVC, animated: true)
    }
} 